name: Remote SSH Command
on:
  push:
    branches: [master, main]

jobs:
  build:
    name: Build and Deploy React App
    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: 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
      PEM_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAqAH5i48hG1UfO8YS0OswPO0h20UePVa0AOQV1ABPHb4ST38w
        3Y5l6iR3/6xXaQepYYFIPPWf6f4pzj4x5UZ+WIMEmwhGjIdzAgHcETo6JBP8Ossw
        n0HnYww7myLfvmdUfM6wKJWeh0sr37uM6jG0ShP13ENFi3DUpV4JztvZz3hyCLsD
        J+X7Ko+zZf7tBUsHJAsTzHpEINoV3BtCq8Myas4UsxqFK3lBv/j7vNGW+LR/0eNP
        gC2kCd7n66IrOoMyAN34nR4fTzAEDXmcnl9eQ0GZiH6OyOGU26kWv/JV/GtPIdtE
        FslPN225Njllv/SyMcgEaVB4dIdPdfjRngvyowIDAQABAoIBAH5VpdHE2i9Ubf0j
        r8h74jUeV8QrkFatmQPGf4eAh/2kjN5MlXE0//v2WmnerYgkI8FXVvvH8+0fm04k
        RJ7UyHNEajUuHubTf671uQcXUtsIUDXhzvkitJ0teLDqo3bo+oYzYhHSmHfCFgbS
        YF9G6vx9T/bGe0gkmzKSqSts9Ldl7YW7WvG8U3ABxpmnO5e4tx8HBoCChQlSL30X
        EorLfMHQKQYeKZPL3OP/NKlQYi/h2HWiyQLXvqfgVIKvJ0UKcfYV8E0oMjGjAJmE
        X4U27344w7F4+FYpXQglYZe/I4VJTFT7jEZBv+cuMqZstoFKZZhc1aWKm+yss+t1
        DipethkCgYEA9USRprhjpd3r6t1uH+kUPrskzmlInHtrNX3Zk9W2QC9syNdscDkQ
        1MgdzvSHBSl7TZFRQIARzw9R0ORneo99OMqXFQe4bPfvH/hUPQtrKtZKUFylWXOW
        ahxKqD+3jNaip/lEOpxwlwUAt5RYD9UP9B13/cJ97Upn6DbvI/SYxAUCgYEAr1v0
        3s0hvKLETItMhVMsHR7+Zc4Igo/lDTkV6LyoojoQ9LiFdKYpu4Hw7/MjDlswcleI
        +D6Ph+mAkEMW623zYwfOPsqn6rbvAsfUBi47RBGTA1J2YVI69WE2ebHfH7W5hIDV
        PgH65FuD7nSZ8KWYw/IGfWE3op9RKQX2uZDihIcCgYAz3NX3rRHVJwIV3dDFiqGv
        Sh9UTkr+W9KlswDpE82/8MdOCM9zQ33doJs9AdPzMXxTQKEvxGT/pbulMkb3UZQn
        CB++YK2MzTiRSA94AQweOMXqDE0ihyCNO4JF5YNIkrI+VqUox5+/L12hdArS/jir
        Y/fVfuTl4k/qeINE1RngiQKBgQCp/z5io4AaK7ya68ux0FCKppo+vT64u6B0civQ
        JNxh8GKxqxQNYmxAj5awNwd8CmDr5/orlhJ00qPEtpVIhJ2XGmERtEqWmuMX0fq0
        RytDMLpRVSbX7+yiJqy1yv6f8f63+mE/LJI5wJIkn7sAdLik9ELgV1ek+kemulZV
        zKQbjwKBgFLuknXOdDJYyS6c7wZOt82BIfeVf0UHJOKnyoym9PmpC9lbctTePRvj
        h2R3nupHy923LYQ2c6/92MyPgWKr/2Pih2WtHm+Sk/9XCgyUgWgvjEleakdE9XMA
        andn2TtgpxwjUAaQ0wQWkNvTG367ZADDAcSIRAoOF9P+MxPQakyK
        -----END RSA PRIVATE KEY-----

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Connect to Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: 35.171.140.25
        username: ubuntu
        key: ${{ env.PEM_KEY }}
        port: 22
        script: |
          whoami # Debugging: Show current user

          # Set up repository variables
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          REPO_DIR="/var/www/$REPO_NAME"

          # Klonlama veya güncelleme işlemi
          if [ ! -d "$REPO_DIR" ]; then
            echo "Repository bulunamadı, klonlama yapılıyor..."
            git clone https://rovshanguli:${{ env.GIT_TOKEN }}@github.com/${{ github.repository }}.git $REPO_DIR
            echo "Repository başarıyla klonlandı."
          else
            echo "Repository mevcut. Güncellemeler çekiliyor..."
            cd $REPO_DIR
            git pull origin main
          fi

          # Build işlemi
          cd $REPO_DIR
          echo "Bağımlılıklar yükleniyor ve proje build ediliyor..."
          npm install
          npm run build

          # Nginx yapılandırması
          NGINX_CONFIG="/etc/nginx/sites-available/$REPO_NAME"
          NGINX_LINK="/etc/nginx/sites-enabled/$REPO_NAME"

          echo "Nginx yapılandırma dosyası oluşturuluyor veya güncelleniyor..."
          echo "server {
              listen 80;
              server_name $REPO_NAME.com www.$REPO_NAME.com;

              root /var/www/$REPO_NAME/build;
              index index.html index.htm;

              location / {
                  try_files \$uri /index.html;
              }
          }" | sudo tee $NGINX_CONFIG

          # Sembolik link kontrolü ve oluşturma
          if [ ! -L "$NGINX_LINK" ]; then
            echo "Nginx konfigürasyonu için sembolik link oluşturuluyor."
            sudo ln -s $NGINX_CONFIG $NGINX_LINK
          fi

          # Nginx yapılandırmasını yeniden başlatma
          echo "Nginx yeniden başlatılıyor..."
          sudo nginx -t
          sudo systemctl restart nginx